services:
  - type: web
    name: ppadun9-game-operation
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: member-management
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: member-management-secret-key-2024
    healthCheckPath: /
    autoDeploy: true
    plan: free
