services:
  - type: web
    name: ppadun9-game-operation
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: ppadun9-game
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: free
